#!/usr/bin/env bash
# Regenerate SKILLS.md — the cheap, one-line-per-skill index agents read to decide what to
# load. Run after adding, removing, or renaming a skill in .agents/skills/.
set -euo pipefail
root="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
cd "$root"
out="SKILLS.md"
{
  echo "# Skill index"
  echo
  echo "<!-- GENERATED by .agents/tools/skills-index.sh — do not edit by hand. -->"
  echo
  echo "Every skill available to an agent in this repository. Read **this file**, not the"
  echo "skills themselves, to decide what to load — it is a few hundred tokens; loading all"
  echo "skill bodies is tens of thousands."
  echo
  echo "Generated: $(date '+%Y-%m-%d %H:%M')  ·  $(ls -1d .agents/skills/*/ 2>/dev/null | wc -l | tr -d ' ') skills"
  echo
  echo "| Skill | Use when | Path |"
  echo "|---|---|---|"
  for d in .agents/skills/*/; do
    n="$(basename "$d")"
    [ -f "$d/SKILL.md" ] || continue
    desc="$(awk '
      /^---$/{c++; next}
      c==1 && /^description:/{sub(/^description:[[:space:]]*/,""); print; exit}
    ' "$d/SKILL.md" | tr -d '"' | tr '\n' ' ' | sed 's/[[:space:]]\+/ /g' | sed 's/^ //; s/ $//')"
    case "$desc" in '>'|'|'|'') desc="(no description)";; esac
    case "$desc" in \|*) desc="\\$desc";; esac
    printf '| `%s` | %s | `%s` |\n' "$n" "${desc:0:200}" "${d}SKILL.md"
  done
} > "$out"
printf 'wrote %s (%s skills)\n' "$out" "$(grep -c '^| `' "$out")"
