import type { BusinessId, Money, DateRange } from '@/lib/types';
import type { HalfOpenPeriod, BucketGranularity } from '@/modules/analytics';
import type { DataQuality } from '@/modules/analytics';

/**
 * Cash-flow intelligence types.
 *
 * The central design rule of this module is that a forecast is never presented as
 * a fact. Every line item carries a `confidence`, every forecast carries its
 * assumptions, and every forecast carries a coverage score. A consumer can always
 * tell which numbers were observed, which were promised by a dated obligation,
 * and which were extrapolated.
 */

/**
 * How a projected line came to exist.
 *
 *   actual   — observed inside the period from the ledger. A fact.
 *   expected — a dated obligation with a known amount and due date (an open
 *              receivable, an open payable, a dated or recurring expense).
 *              A commitment, not yet a fact.
 *   projected — extrapolated from historical behaviour. The weakest tier, and
 *              the only one that involves an assumption.
 */
export type CashFlowConfidence = 'actual' | 'expected' | 'projected';

export type CashFlowCategory =
  | 'sales_revenue'
  | 'collections'
  | 'other_income'
  | 'supplier_payments'
  | 'operating_expenses'
  | 'salaries'
  | 'rent'
  | 'taxes'
  | 'loan_payments'
  | 'planned_purchases'
  | 'other_expenses';

export type RiskType =
  | 'negative_balance'
  | 'low_balance'
  | 'high_concentration'
  | 'payment_spike';

export type RiskSeverity = 'critical' | 'warning' | 'info';

export interface CashFlowItem {
  readonly category: CashFlowCategory;
  /** Integer minor units. Never negative. */
  readonly amount: number;
  readonly description: string;
  readonly confidence: CashFlowConfidence;
  /** Stable id of the record or rule that produced this line. */
  readonly sourceId?: string;
  /** The source table or derivation, so the UI can offer a provenance link. */
  readonly sourceType?: CashFlowSourceType;
  /** True when the line was generated by an assumption rather than a record. */
  readonly assumptionBased: boolean;
}

export type CashFlowSourceType =
  | 'transaction'
  | 'receivable'
  | 'payable'
  | 'expense'
  | 'recurring_expense'
  | 'historical_average'
  | 'derived';

export interface CashFlowPeriod {
  readonly periodStart: Date;
  readonly periodEnd: Date;
  readonly inflows: readonly CashFlowItem[];
  readonly outflows: readonly CashFlowItem[];
  /** inflows - outflows, in minor units. */
  readonly netFlow: number;
  /** Balance at the end of this period, carried from the previous one. */
  readonly runningBalance: number;
}

/** One explicit, auditable statement of what the projection assumes. */
export interface ForecastAssumption {
  readonly id: string;
  readonly statement: string;
  readonly category: CashFlowCategory;
  /** Share of this category's projected total that depends on the assumption. */
  readonly shareBps: number | undefined;
  /** Human-readable effect of the assumption being wrong. */
  readonly limitation: string;
}

export interface CashFlowRisk {
  readonly type: RiskType;
  readonly severity: RiskSeverity;
  readonly periodStart: Date;
  readonly description: string;
  /** Positive number of minor units the merchant is short. */
  readonly projectedShortfall?: number;
  readonly contributingFactors: readonly string[];
  /** Stable id so the UI and the model can link to the underlying records. */
  readonly relatedIds: readonly string[];
}

/**
 * How completely the projection is backed by source records.
 *
 *   coverageBps          share of projected magnitude backed by a dated obligation
 *   historicalWindowDays length of history used for any extrapolation
 *   hasEnoughHistory     at least `MIN_HISTORY_PERIODS` prior periods exist
 *   quality              worst status across the inputs
 */
export interface ForecastCoverage {
  readonly coverageBps: number;
  readonly historicalWindowDays: number;
  readonly periodsOfHistory: number;
  readonly hasEnoughHistory: boolean;
  readonly quality: DataQuality;
  readonly knownGaps: readonly string[];
}

export interface CashFlowForecast {
  readonly id: string;
  readonly businessId: BusinessId;
  readonly period: DateRange;
  readonly periods: readonly CashFlowPeriod[];
  readonly startingCash: Money;
  readonly endingCash: Money;
  readonly risks: readonly CashFlowRisk[];
  readonly calculatedAt: Date;
  readonly currency: string;
  readonly reportingTimezone: string;
  readonly granularity: BucketGranularity;
  readonly assumptions: readonly ForecastAssumption[];
  readonly coverage: ForecastCoverage;
  /**
   * Always true for a forecast produced by this module. Present so a consumer
   * can assert the distinction programmatically instead of inferring it from
   * the field name.
   */
  readonly isProjection: true;
  /** The ledger-derived cash this projection starts from, and its provenance. */
  readonly openingBalanceSource: OpeningBalanceSource;
}

export type OpeningBalanceSource = 'ledger_derived' | 'unavailable';

/** Input facts for a projection, gathered by the application layer. */
export interface CashFlowInputs {
  readonly businessId: BusinessId;
  readonly currency: string;
  readonly timezone: string;
  readonly horizon: HalfOpenPeriod;
  readonly openingCashMinor: number;
  readonly openingBalanceSource: OpeningBalanceSource;
  readonly receivables: readonly ObligationInput[];
  readonly payables: readonly ObligationInput[];
  readonly datedExpenses: readonly DatedExpenseInput[];
  readonly recurringExpenses: readonly RecurringExpenseInput[];
  /** Historical inflow total per past period, oldest first. Drives extrapolation. */
  readonly historicalInflows: readonly { readonly from: Date; readonly to: Date; readonly inflowMinor: number }[];
  readonly historicalWindowDays: number;
  readonly asOf: Date;
}

/** Recurring expense categories are mapped onto cash-flow categories, not copied. */
export type RecurringFrequency =
  | 'daily'
  | 'weekly'
  | 'monthly'
  | 'quarterly'
  | 'yearly';

/**
 * Facts gathered by the application layer and handed to the pure engine.
 *
 * Keeping this a plain data shape is what allows the projection to be tested
 * without a database and guarantees the engine cannot reach outside itself.
 */
export interface CashFlowInputs {
  readonly businessId: BusinessId;
  readonly currency: string;
  readonly timezone: string;
  readonly horizon: HalfOpenPeriod;
  readonly openingCashMinor: number;
  readonly openingBalanceSource: OpeningBalanceSource;
  readonly receivables: readonly ObligationInput[];
  readonly payables: readonly ObligationInput[];
  readonly datedExpenses: readonly DatedExpenseInput[];
  readonly recurringExpenses: readonly RecurringExpenseInput[];
  /** Historical inflow per prior period, oldest first. Drives extrapolation. */
  readonly historicalInflows: readonly HistoricalPeriodInput[];
  readonly historicalWindowDays: number;
  readonly asOf: Date;
}

export interface HistoricalPeriodInput {
  readonly from: Date;
  readonly to: Date;
  readonly inflowMinor: number;
}

export interface ObligationInput {
  readonly id: string;
  readonly counterpartyId: string;
  readonly counterpartyName: string;
  readonly openMinor: number;
  readonly dueDate: Date;
  readonly daysOverdue: number;
}

export interface DatedExpenseInput {
  readonly id: string;
  readonly category: string;
  readonly amountMinor: number;
  readonly expenseDate: Date;
}

export interface RecurringExpenseInput {
  readonly id: string;
  readonly category: string;
  readonly amountMinor: number;
  readonly frequency: RecurringFrequency;
  readonly nextDueDate: Date;
  readonly endDate: Date | null;
}

export { HalfOpenPeriod, BucketGranularity };

/** All assumptions behind one projection. Never empty in practice. */
export type CashFlowAssumptions = readonly ForecastAssumption[];

/** The engine's output before the application layer attaches identity and storage. */
export interface CashFlowProjection {
  readonly periods: readonly CashFlowPeriod[];
  readonly openingBalanceMinor: number;
  readonly endingCashMinor: number;
  readonly assumptions: CashFlowAssumptions;
  readonly coverage: ForecastCoverage;
  readonly risks: readonly CashFlowRisk[];
}