export const DATABASE_TABLES = {
  businesses: 'businesses',
  businessMembers: 'business_members',
  users: 'users',
  transactions: 'transactions',
  transactionItems: 'transaction_items',
  expenses: 'expenses',
  products: 'products',
  inventoryMovements: 'inventory_movements',
  customers: 'customers',
  receivables: 'receivables',
  suppliers: 'suppliers',
  payables: 'payables',
  supplierPricing: 'supplier_pricing',
  documents: 'documents',
  ingestionJobs: 'ingestion_jobs',
  extractions: 'document_extractions',
  profitLeaks: 'profit_leaks',
  cashFlowForecasts: 'cash_flow_forecasts',
  scenarios: 'scenarios',
  actions: 'actions',
  actionLogs: 'action_logs',
  embeddings: 'document_embeddings',
  chatSessions: 'chat_sessions',
  chatMessages: 'chat_messages',
  notifications: 'notifications',
  auditLogs: 'audit_logs',
} as const;

export type TableName = (typeof DATABASE_TABLES)[keyof typeof DATABASE_TABLES];
