-- Stable keyset order for durable chat; existing tenant/user RLS remains in force.
-- Backfill legacy messages by creation time only on the initial column addition.
-- Re-running never renumbers active conversations or invalidates their cursors.
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_catalog.pg_attribute
    WHERE attrelid = 'public.chat_messages'::regclass
      AND attname = 'position' AND NOT attisdropped
  ) THEN
    ALTER TABLE public.chat_messages ADD COLUMN position bigint GENERATED BY DEFAULT AS IDENTITY;
    WITH ordered AS (
      SELECT id, row_number() OVER (ORDER BY created_at, id) AS position
      FROM public.chat_messages
    )
    UPDATE public.chat_messages AS m SET position = ordered.position
    FROM ordered WHERE m.id = ordered.id;
    PERFORM pg_catalog.setval(
      pg_catalog.pg_get_serial_sequence('public.chat_messages', 'position')::regclass,
      GREATEST(COALESCE((SELECT max(position) FROM public.chat_messages), 0), 1),
      EXISTS (SELECT 1 FROM public.chat_messages)
    );
    ALTER TABLE public.chat_messages ALTER COLUMN position SET GENERATED ALWAYS;
  END IF;
END;
$$;
CREATE UNIQUE INDEX IF NOT EXISTS idx_chat_messages_position ON public.chat_messages (position);
CREATE INDEX IF NOT EXISTS idx_chat_messages_session_position ON public.chat_messages (session_id, position DESC);
